/*
 * MSYSTICK_config.h
 *
 *  Created on: Aug 15, 2023
 *      Author: Mostafa_Salem
 */

#ifndef MCAL_MSYSTIKC_MSYSTICK_CONFIG_H_
#define MCAL_MSYSTIKC_MSYSTICK_CONFIG_H_


#define SYSTICK_CLOCK_SOURCE	AHB_CLOCK		// AHB_CLOCK	OR		AHB_CLOCK_DIV_8
#define SYSTICK_AHB_CLOCK		16000000				// AHB clock 16MHz

#endif /* MCAL_MSYSTIKC_MSYSTICK_CONFIG_H_ */
